apiVersion: batch/v1
kind: CronJob
metadata:
  name: insights-expire-listings
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: expire-listings
            image: registry.digitalocean.com/poestack/sage:latest
            command: ["node"]
            args: ["src/insights/dist/expire-listings.js"]
            envFrom:
              - secretRef:
                  name: sage-secrets
          restartPolicy: OnFailure

